favicon: null
project:
  type: website
  output-dir: docs

website:
  title: "Jamie Parton"
  navbar:
    background: light

    # left:
#      - text: Home
#        href: index.qmd
      # - text: Projects
      #  href: "#"
      # - text: Publications
      #  href: "#"                        
      # - text: Photography
      #  href: "#"            
      # - text: News
      #  href: "#"
      # - text: "CV"
      #qq  href: "#"

  page-navigation: false

  page-footer: 
    left: "© Jamie Parton 2025" 
    right:  
      - icon: envelope
        href: mailto:jlp2g21@soton.ac.uk  
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/jamieparton/
        target: _blank
      - icon: researchgate
        href: https://www.researchgate.net/profile/Jamie-Parton?ev=hdr_xprf
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""  
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    extensions: [fontawesome]
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: 
    - "files/includes/_academic.qmd"
    - google-analytics.html

